version: '3.8'

services:
  app:
    build: .
    container_name: php-app
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=todo_db
      - DATABASE_USER=todo_user
      - DATABASE_PASSWORD=password
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: